[package]
name = "ufos"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
clap = { version = "4.5.31", features = ["derive"] }
jetstream = { path = "../jetstream" }
serde_json = "1.0.140"
tokio = { version = "1.43.0", features = ["full", "sync", "time"] }
