[workspace]
resolver = "2"
members = [
    "links",
    "constellation",
    "jetstream",
    "ufos",
]

[patch.crates-io]
lsm-tree = { git = "https://github.com/fjall-rs/lsm-tree.git", branch = "fix/lockless-ranges" }
