name: checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
    - name: Build lib
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  style:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: fmt
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy --all-targets --all-features -- -D warnings
